# Generated by Django 4.2.2 on 2023-07-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='companycontact',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='companyemail',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='contact',
        ),
        migrations.AddField(
            model_name='detail',
            name='profileimage',
            field=models.ImageField(default='ad', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='companylogo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
